build_from:
  aarch64: "lscr.io/linuxserver/oscam:arm64v8-latest"
  amd64: "lscr.io/linuxserver/oscam:amd64-latest"   
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: OSCam"
  org.opencontainers.image.description: "OSCam addon"
  org.opencontainers.image.source: "https://github.com/dmdias/homeassistant-addons"  # Update with your repo URL
  org.opencontainers.image.licenses: "Apache License 2.0"
args:
  TEMPIO_VERSION: "2024.09.03"
