name: "OSCam Addon"
version: "1.0.6"
slug: "oscam_addon"
description: "An OSCam add-on using the LinuxServer Docker image."
url: https://github.com/dmdias/homeassistant-addons/tree/main/oscam-addon
#webui: "http://[HOST]:[PORT:8889]"
init: false
ingress: true
ingress_port: 8888
ingress_stream: true
arch:
  - amd64
  - aarch64
ports:
  8888/tcp: 8889
  1000/tcp: 1001
  22/tcp: 8822
map:
  - share:rw
  - ssl:rw
image: "ghcr.io/dmdias/{arch}-addon-oscam"