build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.15"
  amd64: "ghcr.io/home-assistant/amd64-base:3.15" 
  #aarch64: "linuxserver/oscam:arm64v8-latest"
  #amd64: "linuxserver/oscam:amd64-latest"   
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: OSCam"
  org.opencontainers.image.description: "OSCam addon"
  org.opencontainers.image.source: "https://github.com/dmdias/homeassistant-addons"  # Update with your repo URL
  org.opencontainers.image.licenses: "Apache License 2.0"
args:
  TEMPIO_VERSION: "2024.09.03"  # Specify the version of any dependencies if needed
