name: "OSCam Addon"
version: "1.0.2"
slug: "oscam_addon"
description: "An OSCam add-on using the LinuxServer Docker image."
webui: "http://[HOST]:[PORT:9000]"  # Change to the appropriate port
arch:
  - amd64
  - aarch64
ports:
  8888/tcp: 8889
  1000/tcp: 1001
map:
  - homeassistant_config:rw
  - ssl:rw
image: "ghcr.io/dmdias/{arch}-addon-oscam"