name: "OSCam Addon"
version: "1.0.0"
slug: "oscam_addon"
description: "An OSCam add-on using the LinuxServer Docker image."
webui: "http://[HOST]:[PORT:9000]"  # Change to the appropriate port
arch:
  - amd64
  - aarch64
ports:
  8888/tcp: 9000
map:
  - homeassistant_config:rw
  - ssl:rw
#image: "ghcr.io/linuxserver/oscam:latest"  # Change to the correct image if needed
image: "ghcr.io/danieldias/{arch}-addon-oscam"