ARG ARCH
FROM ghcr.io/linuxserver/oscam:${ARCH}-latest 
EXPOSE 9000
#FROM ghcr.io/linuxserver/oscam:latest  # Use the appropriate OSCam image

# Add any additional configuration or scripts if necessary
