# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
#FROM linuxserver/oscam:latest
ARG BUILD_FROM
FROM $BUILD_FROM

#FROM linuxserver/oscam:arm64v8-latest

EXPOSE 8888 9000