# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: ElasticSearch
version: "1.2.0"
slug: ElasticSearch
description: ElasticSearch
url: "https://github.com/dmdias/homeassistant-addons/tree/main/ElasticSearch"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  message: "ElasticSearch"
schema:
  message: "str?"
image: "ghcr.io/danieldias/{arch}-addon-elasticsearch"