# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.15"
  amd64: "ghcr.io/home-assistant/amd64-base:3.15"  
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: OScam"
  org.opencontainers.image.description: "Oscam addon"
  org.opencontainers.image.source: "https://github.com/home-assistant/oscam"
  org.opencontainers.image.licenses: "Apache License 2.0"
args:
  TEMPIO_VERSION: "2024.09.03"