name: "OSCam Addon"
version: "1.0.0"
slug: "oscam_addon"
description: "An OSCam addon using the LinuxServer Docker image"
startup: "services"
webui: "http://[HOST]:[PORT:9000]"
arch: 
  - i386
  - aarch64
  - amd64
ports:
  8888/tcp: 8888
  9000/tcp: 9000
map:
  - config:rw
  - ssl:rw
image: "linuxserver/oscam:latest"
url: "https://github.com/linuxserver/docker-oscam"  # Optional field