# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Oscam Addon
version: "1.0.1"
slug: Oscam Addon
description: An OSCam addon using the LinuxServer Docker image
arch:   
  - amd64
  - aarch64  
ports:
  8888/tcp: 8888
  9000/tcp: 9000
map:
  - homeassistant_config:rw
#image: linuxserver/oscam:latest
image: "ghcr.io/danieldias/{arch}-addon-oscam"